config/routes.rb
Kasapi::Application.routes.draw do
  devise_for :admins
  namespace :admin do
    resources :users, :only => [:index, :edit, :update]
    resources :campaigns
    resources :orders
  end
  
  devise_for :users
  resources:users
  resources :campaigns
  resources :orders
  
  root :to => 'admin/users#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
  has_many :campaigns
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  attr_accessible :description, :admin_id, :name, :price
  
  belongs_to :admin
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :campaign_id, :customer_id, :name
  
  belongs_to :campaign
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/admin/campaigns_controller.rb
class Admin::CampaignsController < ApplicationController
  before_filter :authenticate_admin!
  def index
    @campaign = current_admin.campaigns
  end
  
  def show
     @campaign = Campaign.find(params[:id])
  end
  
  def new
  end
  
  def edit
  end
  
  def create
  end
  
  def update
  end
  
  def destroy
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :authenticate_admin!
  
  def index
    @admin = current_admin
  end
  
  def edit
  end
  
  def update
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  def index
    @user = current_user
    redirect_to @user
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def edit
  end
  
  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/campaigns/index.html.erb
<h1> Campaigns</h1>
<table>
  <tr>
    <th>#</th>
    <th>Campaign Name</th>
  </tr>

<% count = 0 %>
<% @campaign.each do |campaign| %>
  <% count = count + 1%>
  <tr>
    <td><%= count %></td>
    <td><%= campaign.name %></td>
    <td><%= link_to 'View Orders', admin_campaign_path(campaign) %></td>
    <td><%= link_to 'Edit', '#' %></td>
    <td><%= link_to 'Delete', '#' %></td>
  </tr>
<% end %>
</table>

<br/>

<%= link_to 'Create New Campaign', '#' %> | 
<%= link_to 'Back to Home', admin_users_path %>

app/views/admin/campaigns/show.html.erb
<h1><%= @campaign.name %></h1>

<h2>Details:</h2>
<p>
Price: <%= @campaign.price %> <br/>
Description: <%= @campaign.description %> <br/>
</p>

<h2>Orders:</h2>
<table>
  <tr>
    <th>Purchaser's Email</th>
  </tr>
</table>

<%= link_to 'Back to Campaigns', admin_campaigns_path %> | 
<%= link_to 'Back to Home', admin_users_path %>

app/views/admin/users/index.html.erb
<h1> Hello <%= @admin.email %> </h1>
<%= link_to 'Edit Profile', '#' %> | 
<%= link_to 'Campaigns', admin_campaigns_path %> |
<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kasapi</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/show.html.erb
<h1> Hello <%=@user.email%> </h1>